# Generated by Django 3.1.5 on 2021-04-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aashray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
